var app=angular.module('myApp',['ngRoute']);
app.config(['$routeProvider',function($routeProvider){
	$routeProvider
	.when('/',{
		templateUrl:'./views/home.html',
		controller:'homeCtrl'
	})
	.when('/home',{
		templateUrl:'./views/home.html',
		controller:'homeCtrl'
	})
	.when('/fenlei',{
		templateUrl:'./views/fenlei.html',
		controller:'fenleiCtrl'
	})
	.when('/say',{
		templateUrl:'./views/say.html',
		controller:'sayCtrl'
	})
	.when('/tool',{
		templateUrl:'./views/tool.html',
//		controller:'toolCtrl'
	})
	.when('/mine',{
		templateUrl:'./views/mine.html',
//		controller:'mineCtrl'
	})
	.when('/zhaoshangjia',{
		templateUrl:'./views/zhaoshangjia.html',
		controller:'zhaoshangjiaCtrl'
	})
	.when('/weddingshoes',{
		templateUrl:'./views/weddingshoes.html',
		controller:'myWeddingshoesCtrl'
	})
//	.when('/weddingshoes',{
//		templateUrl:'./views/weddingshoes.html',
//		controller:'myWeddingshoesCtrl'
//	})
	.when('/buyshoes',{
		templateUrl:'./views/buyshoes.html',
		controller:'buyshoesCtrl'
	})
	.when('/book-1',{
		templateUrl:'./views/book-1.html',
	})
	.when('/book-2',{
		templateUrl:'./views/book-2.html',
	})
	.when('/budget-1',{
		templateUrl:'./views/budget-1.html',
	})
	.when('/budget-2',{
		templateUrl:'./views/budget-2.html',
		controller:'budget2Ctrl'
	})
	.when('/map',{
		templateUrl:'./views/map.html',
	})
	.when('/atteneion',{
		templateUrl:'./views/atteneion.html',
	})
	.when('/dingdan',{
		templateUrl:'./views/dingdan.html',
	})
	.when('/huati',{
		templateUrl:'./views/huati.html',
	})
	.when('/huodong',{
		templateUrl:'./views/huodong.html',
	})
	.when('/shangjia',{
		templateUrl:'./views/shangjia.html',
	})
	.when('/shopcar',{
		templateUrl:'./views/shopcar.html',
	})
	.when('/shoucang',{
		templateUrl:'./views/shoucang.html',
	})
	.when('/yuyue',{
		templateUrl:'./views/yuyue.html',
	})
	.otherwise({redirectTo:'/'});
}])
