define(['jquery','hostUrl'],function($,host){
	return{
		getData:function(){
			$.ajax({
				type:"get",
				url:host.hostUrl,
				success:function(response){
					console.log(response);
				}
			});
		},
		postData:function(formData){
			$.ajax({
				type:"post",
				url:host.hostUrl,
				data:formData,
				success:function(response)
				{
					console.log(response);
				}
			});
		},
		deleteData:function(id){
			$.ajax({
				type:"delete",
				url:host.hostUrl+'/'+id,
				success:function(response){
					console.log(response);
				}
			});
		},
		putData:function(id,formData){
			$.ajax({
				type:'put',
				url:host.hostUrl+'/'+id,
				data:formData,
				success:function(response){
					console.log(response);
				}
			})
		},
		showData:function(id){
			$.ajax({
				type:'get',
				url:host.hostUrl+'/'+id,
				success:function(response){
					console.log(response);
				}
			})
		}
	}
})